<a href="https://colab.research.google.com/github/Sukhi24397/Pract0/blob/main/Experiment14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#sukhi n
#25070123112
#data binning and data formatting using python

In [2]:
import pandas as pd
import numpy as np
data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}
df= pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [3]:
#Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
df.head()

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low

In [5]:
#binning uits sold
bins2 = [0,30,60,100]
labels2 = ['Low Sales','Medium Sales','High Sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [9]:
#data formatting
#convert data types

print(df.dtypes)
df['Units_Sold']=df['Units_Sold'].astype(float)
print(df.dtypes)
df

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [10]:
#convert text to uppercse
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [11]:
#convert text to lowercse
df['Product']=df['Product'].str.lower()
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      laptop  55000        25.0           High      Low Sales
1      mobile  20000        60.0         Medium   Medium Sales
2      tablet  30000        35.0         Medium   Medium Sales
3  headphones   2000        80.0            Low     High Sales
4  smartwatch   8000        50.0            Low   Medium Sales
5      camera  45000        15.0           High      Low Sales

In [13]:
#rounding values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      laptop  55000        25.0           High      Low Sales
1      mobile  20000        60.0         Medium   Medium Sales
2      tablet  30000        35.0         Medium   Medium Sales
3  headphones   2000        80.0            Low     High Sales
4  smartwatch   8000        50.0            Low   Medium Sales
5      camera  45000        15.0           High      Low Sales

In [14]:
#additional operations
#sort data
sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  headphones   2000        80.0            Low     High Sales
4  smartwatch   8000        50.0            Low   Medium Sales
1      mobile  20000        60.0         Medium   Medium Sales
2      tablet  30000        35.0         Medium   Medium Sales
5      camera  45000        15.0           High      Low Sales
0      laptop  55000        25.0           High      Low Sales

In [17]:
df.sort_values(by='Units_Sold',inplace=True)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
5      camera  45000        15.0           High      Low Sales
0      laptop  55000        25.0           High      Low Sales
2      tablet  30000        35.0         Medium   Medium Sales
4  smartwatch   8000        50.0            Low   Medium Sales
1      mobile  20000        60.0         Medium   Medium Sales
3  headphones   2000        80.0            Low     High Sales

In [16]:
df.sort_values(by='Units_Sold',ascending=False,inplace=True)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  headphones   2000        80.0            Low     High Sales
1      mobile  20000        60.0         Medium   Medium Sales
4  smartwatch   8000        50.0            Low   Medium Sales
2      tablet  30000        35.0         Medium   Medium Sales
0      laptop  55000        25.0           High      Low Sales
5      camera  45000        15.0           High      Low Sales

In [18]:
#display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [31]:
#dataset:food delivery orders
import pandas as pd
import numpy as np
data = {
'Order_Id': [1,2,3,4,5,6,7,8],
'Order_Value' :[250,450,120,600,300,150,500,220],
'Delivery_Time' :[30,45,25,60,35,20,50,28],
'Distance_km' :[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
print(df)

   Order_Id  Order_Value  Delivery_Time  Distance_km
0         1          250             30            5
1         2          450             45            8
2         3          120             25            3
3         4          600             60           10
4         5          300             35            6
5         6          150             20            2
6         7          500             50            9
7         8          220             28            4

In [37]:
#binning delivery time
bins2 = [0,30,45,70]
labels2 = ['Fast','Medium','Slow']
df['Delivery_Speed'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
print(df)

   Order_Id  Order_Value  Delivery_Time  Distance_km Delivery_speed  \
0         1          250             30            5           Fast
1         2          450             45            8         Medium
2         3          120             25            3           Fast
3         4          600             60           10           Slow
4         5          300             35            6         Medium
5         6          150             20            2           Fast
6         7          500             50            9           Slow
7         8          220             28            4           Fast

  Delivery_Speed
0           Fast
1         Medium
2           Fast
3           Slow
4         Medium
5           Fast
6           Slow
7           Fast

In [38]:
# Binning Distance_km

bins_distance = [0, 4, 8, 12]

labels_distance = ["Short Distance", "Medium Distance", "Long Distance"]

df['Distance_Category'] = pd.cut(df['Distance_km'], bins=bins_distance, labels=labels_distance)

df

,Order_Id,Order_Value,Delivery_Time,Distance_km,Delivery_speed,Delivery_Speed,Distance_Category
0,1,250,30,5,Fast,Fast,Medium Distance
1,2,450,45,8,Medium,Medium,Medium Distance
2,3,120,25,3,Fast,Fast,Short Distance
3,4,600,60,10,Slow,Slow,Long Distance
4,5,300,35,6,Medium,Medium,Medium Distance
5,6,150,20,2,Fast,Fast,Short Distance
6,7,500,50,9,Slow,Slow,Long Distance
7,8,220,28,4,Fast,Fast,Short Distance

In [43]:
#count of categories
# Binning Order_Value
bins_order_value = [0, 200, 400, 600, 800]
labels_order_value = ['Low', 'Medium', 'High', 'Very High']
df['Order_Category'] = pd.cut(df['Order_Value'], bins=bins_order_value, labels=labels_order_value, include_lowest=True)
print(df['Order_Category'].value_counts())
print(df)

Order_Category
Medium       3
High         3
Low          2
Very High    0
Name: count, dtype: int64
   Order_Id  Order_Value  Delivery_Time  Distance_km Delivery_speed  \
0         1          250             30            5           Fast
1         2          450             45            8         Medium
2         3          120             25            3           Fast
3         4          600             60           10           Slow
4         5          300             35            6         Medium
5         6          150             20            2           Fast
6         7          500             50            9           Slow
7         8          220             28            4           Fast

  Delivery_Speed Distance_Category Order_Category
0           Fast   Medium Distance         Medium
1         Medium   Medium Distance           High
2           Fast    Short Distance            Low
3           Slow     Long Distance           High
4         Medium   Medium Distance         Medium
5           Fast    Short Distance            Low
6           Slow     Long Distance           High
7           Fast    Short Distance         Medium