<a href="https://colab.research.google.com/github/Sukhi24397/Pract0/blob/main/Experiment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#sukhi n
#25070123112
#data wrangling

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [4]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [7]:
df1.isna().sum() #columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [8]:
df1.isna().sum(axis=1) #rowwise na values

0    0
1    1
2    2
dtype: int64

In [6]:
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [9]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [10]:
df1.fillna(df1.mean())#mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [12]:
#processing on a dataset-1
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)

In [14]:
df.replace("-",np.nan,inplace=True)
df

/tmp/ipykernel_281/2765716767.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [ ]:
#Step2 replace the '-' with nan
df.replace("-",np.nan,inplace=True)

#convert columns to numeric where needed
df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors='coerce')


df

In [16]:
#step3 missing value check
print("Missing values")
print(df.isnull().sum())

Missing values
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [24]:
#fill the age with mean
df["Age"] = pd.to_numeric(df["Age"], errors='coerce') # Ensure the column is numeric
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

   Roll No   Name    Age  Marks Department  Admission_Date
0      101   Asha  20.00   85.0        CSE             NaN
1      102  Rohan  20.75   90.0         IT             NaN
2      103  Meera  21.00   86.5        CSE             NaN
3      104  Karan  20.00   88.0        CSE             NaN
4      105   Anil  22.00   76.0       E&TC             NaN

/tmp/ipykernel_281/983775962.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [19]:
#fill missisng the marks with median
df["Marks"].fillna(df["Marks"].median(),inplace=True)
print(df)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21   86.5        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

/tmp/ipykernel_281/2876328969.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

In [20]:
#step4 fix the incosntient text formatting
df["Department"]=df["Department"].str.upper()
print(df)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21   86.5        CSE     05-06-2023
3      104  Karan   20   88.0        CSE     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [21]:
 #step 5: convert admission date to standard datetime format

df["Admission_Date"] = pd.to_numeric(df["Admission_Date"], errors='coerce')
print(df)

   Roll No   Name  Age  Marks Department  Admission_Date
0      101   Asha   20   85.0        CSE             NaN
1      102  Rohan  NaN   90.0         IT             NaN
2      103  Meera   21   86.5        CSE             NaN
3      104  Karan   20   88.0        CSE             NaN
4      105   Anil   22   76.0       E&TC             NaN